# Created with https://github.com/dart-lang/mono_repo
language: dart

jobs:
  include:
    - stage: analyze_and_format
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="reflutter"
      dart: dev
    - stage: analyze_and_format
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="reflutter_generator"
      dart: dev
    - stage: build
      script: ./tool/travis.sh command
      env: PKG="reflutter_test"
      dart: dev
    - stage: analyze_and_format
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="reflutter_test"
      dart: dev
    - stage: unit_test
      script: ./tool/travis.sh test
      env: PKG="reflutter_test"
      dart: dev

stages:
  - build
  - analyze_and_format
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master,release]

cache:
  directories:
    - $HOME/.pub-cache
