name: reflutter_generator
description: >
  A library to generate HTTP clients from metadata specified by users.
  The thought is that this can be used by Flutter based mobile apps to
  connect to their backend resources.
homepage: https://www.github.com/ctartamella/reflutter
version: 0.3.0
author: Chris Tartamella <chris@tartamella.me>

environment:
  sdk: '>=2.0.0-dev.66.0 <2.0.0'

dependencies:
  meta: ^1.1.5
  analyzer: ^0.32.2
  build: ^0.12.7
  code_builder: ^3.1.1
  dart_style: ^1.1.1
  logging: ^0.11.3+1
  source_gen: ^0.8.2
  reflutter: ^0.3.0
  path: ^1.6.1 # Temporary
  
dev_dependencies:
  build_runner: ^0.9.1